### ISSUE TITLE
Recognize results are lost when transferring files to other user

### ISSUE THREAD

**Issue by andreaskoelsch** [nextcloud/recognize#1118]
### Which version of recognize are you using?

6.1.1

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Files App

### Which Nextcloud version do you have installed?

28.0.4

### Which Operating system do you have installed?

Debian 12

### Which database are you running Nextcloud on?

MariaDB 10.11.6

### How much RAM does your server have?

16GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

When files are transferred from one user to another user via transfer ownership, only the classification results are transferred, face detections are lost. Also, the transferred files are not added to the face detection queue for detecting the faces again.

### Expected Behavior

Either keep the face recognition and run the clustering for the new user or re-run both face recognition and clustering after moving the files.

### To Reproduce

- Upload images to one user
- let recognize do its thing
- transfer ownership of these images to another user
- see that face detections are lost and files are not added to face detection queue

**Comment by andreaskoelsch** [comment]
PS: When moving files to a Group Folder, both face detection and object classification are re-triggered. Is this intended or worth a separate issue?

**Comment by andreaskoelsch** [comment]
It gets even more odd. I just realized, when I move separate files to Group Folders, they are triggered. If I move entire folders, on the other hand, the contained files are not triggered. Pretty sure this is not what's intended

**Comment by andreaskoelsch** [comment]
PPS: Even though the files which are moved separately to Group Folders are reprocessed by recognize, the faces do not show up for the other users, but only for the one who moved them there. Current workaround: move the files/folders via the filesystem and re-scan the directories. That way, they are reprocessed and the results show up for all users in the Group Folder.

**Comment by marcelklehr** [comment]
Hello @andreaskoelsch 

Thank you for this detailed analysis! File transfer to other users is a relatively new feature in nextcloud, so we haven't integrated with this feature yet. I'll also look into the other issues you found.

**Comment by andreaskoelsch** [comment]
Great, looking forward to testing it 😊

**Comment by andreaskoelsch** [comment]
I just found the time to test this today. Seems, it's still not fixed, as the face clustering is not triggered. When I move a file from my personal space to a group folder, it gets added to the classify and face recognitiion queues. However, after the predictions, the detected faces are not added to the clustering. In my own profile, the face recognition works, because it was already detected before moving the file to the group folder. However, other users of the group folder do not get a face recognition

**Comment by marcelklehr** [comment]
Mh, that may be because group folders are not technically shares, while I've been using the share manager to enumerate users with access. I'll change that to use the mount cache instead...

**Comment by marcelklehr** [comment]
Hey @andreaskoelsch 
I've prepared a beta version with a potential fix. Could you try this https://github.com/nextcloud/recognize/releases/tag/v7.0.2-beta.1 and report back here?

**Comment by andreaskoelsch** [comment]
Yes, we're almost there ;-) Thanks for the beta, I just tested it by uploading a picture of myself and moving it to a group folder. What happened after moving the file:
- re-triggered face and imagenet classification
- found face
- 1 face left for clustering, planned tasks: 0

So, what's left is that the clustering needs to trigger a new task after the face detection.

Also, what I found not ideal: After moving the file to the group folder, the classification labels are already available for both users before the imagenet executes again. It seems, they are already transferred with the file and another imagenet execution could be avoided for energy efficiency. Also, this makes me wonder if it would maybe be possible to transfer the face detection in a similar way to the imagenet labels, so the other group users would only need to run the clustering of the newly available faces instead of having to re-run the face detection. However, face detection is cheap, so if this is hard to implement, I won't complain

**Comment by marcelklehr** [comment]
No new classification should be run when moving files :/

**Comment by andreaskoelsch** [comment]
Yes, absolutely. That was already the case in the comment above (https://github.com/nextcloud/recognize/issues/1118#issuecomment-2037712967)

**Comment by marcelklehr** [comment]
Can you try moving a folder with a file in it, to check if the face detections get copied to the groupfolder users? Then all i have to fix is the re-classification.

**Comment by andreaskoelsch** [comment]
I just tested this, i.e.moving a folder containing a file with a face detection to a group folder. After moving the entire folder, neither face detection nor clustering nor imagenet classification are triggered for this file.

The original user of the file still sees the face detection and classification labels of the file. Other users only see the classification labels, but no face detection. I also checked the unassigned faces tab, but nothing there.

**Comment by marcelklehr** [comment]
And just as a sanity check, when moving the folder to a shared folder, does the face detection show up for the sharees of that share?

**Comment by andreaskoelsch** [comment]
Is that question answered with the second paragraph of my last comment? otherwise, I don't understand it.. To repeat, only the original user sees the face detection of that file.

Btw, thanks for the quick replies ❤️

**Comment by marcelklehr** [comment]
Sorry, I will explain. There's groupfolders and there is normal shared folders (ie. a folder that a user shared with some other users). Could you repeat your experiment but instead of moving the folder with face pictures into a group folder, could you move it into a normal folder that is simply shared with some users? The question is again, does this copy the face detections to the other users. (From a technical perspective, groupfolders and shared folders are vastly different beasts)

**Comment by andreaskoelsch** [comment]
Ohh, gotcha. So, I tried sharing this folder with one image inside with another user. Interestingly, recognize then showed 2 faces left for clustering, 0 planned tasks. Not sure, why two faces.. anyways, I ran `occ recognize:cluster-faces` manually and the second user also shows the face.

```
ClusterDebug: Retrieving face detections for user testuser
ClusterDebug: Found 2 fresh detections. Adding 0 old detections and 2078 sampled detections from already existing clusters. Calculating clusters on 2080 detections.
ClusterDebug: Clustering complete. Total num of clustered detections: 2

```

**Comment by marcelklehr** [comment]
Ok. So, to summarize:

 * groupfolders still don't work
 * moving files triggers new classifications

**Comment by andreaskoelsch** [comment]
Not quite. Let me give a more detailed summary.

- Shared Folder:
  - Sharing a folder with a selfie inside says 2 new faces in the recognize admin panel, even though there's just one detection there. Also, this requires a manual call of clustering, then it works for all sharees
  - Moving the selfie to an already existing share works (only one new face waiting for clustering), but requires manual call of clustering. Afterwards, both sharees see the detection
  - Moving a folder with the selfie inside to an already exising shared folder does not work. No new detections for the sharees.

- Group folders:
  - Moving the selfie to the group folder retriggers face and imagenet classifications. Afterwards, it says 1 new detections, 0 planned tasks. After manual clustering call, all group folder users see the detection.
  - Moving the folder with the selfie inside to a group folder neither triggers a classification nor are there new detections. Very much like in the third case above.


So moving individual files works for both sharing and group folders, but requires manual clustering call and causes unnecessary classifications in case of group folders. Moving folders with files inside does not work.

**Comment by marcelklehr** [comment]
So, I believe I've found the culprit. I'll make available a new beta later today, so you can test :)

**Comment by marcelklehr** [comment]
Nope, I still haven't published the beta, sorry.

**Comment by andreaskoelsch** [comment]
no worries, it's not urgent

**Comment by marcelklehr** [comment]
here you go :) https://github.com/nextcloud/recognize/releases/tag/v7.0.2-beta.2

**Comment by marcelklehr** [comment]
> Unfortunately, the moved files are still added to both face recognition and imagenet queues

I think I've fixed that now, too.

**Comment by andreaskoelsch** [comment]
Locally? At least not in the current beta

**Comment by marcelklehr** [comment]
> Locally? At least not in the current beta

Yes, not in the beta, sorry, in the repo :)

**Comment by andreaskoelsch** [comment]
Today, I had a case of a moved folder. Face detections were not copied to other users. So, this is still not working. I can do some more testing with the next version

**Comment by marcelklehr** [comment]
I've published a new release just now with the fix

**Comment by andreaskoelsch** [comment]
Thanks for the effort. I just tested it and it seems the classification is now broken completely. I created a new ticket for this, as it's probably more urgent (https://github.com/nextcloud/recognize/issues/1154)

**Comment by andreaskoelsch** [comment]
Thanks for the quick fix to above issue. I tested again now. Moving files works as expected now, moving folders with files inside them still not.

**Comment by marcelklehr** [comment]
I'll look into this soon.

**Comment by andreaskoelsch** [comment]
Thanks for the message, it's alright for me. At least it works now by moving files instead of folders, so there is a simple workaround for the issue

**Comment by marcelklehr** [comment]
This was fixed with Nextcloud 32.

**Comment by andreaskoelsch** [comment]
> No new classification should be run when moving files :/ Are you sure that another face classification is run on the file? The face detection should just be copied.

I think, this issue was re-introduced with NC 32. Did not test it with a ownership transfer, but by moving a file to a group folder. face detection and classification get retriggered.

**Comment by marcelklehr** [comment]
It depends a bit on how the move is realized internally, I think. If the move is done by copying and deleting the old node, then there is nothing recognize can do, I think.

**Comment by andreaskoelsch** [comment]
I just checked again with a few files.
- Uploaded to my account. Face and object detection run.
- Move to group folder
- Face and object detection run again

However, interestingly the object classes are already available for all the group folder users, so they are transferred over correctly. But then wrongly added to the queue.
Also the face detections seem to be copied over to the other users, because the cluster queue is already filled before the face detection is run again.

I'll open an issue on group folders to understand if this double detection runs can be avoided.

**Comment by andreaskoelsch** [comment]
Just wanted to check in again on this issue. Current behavior: Both face and object detection run when I upload files. After I move the files to a group folder, they run again. However, face detections are only visible in the user account who uploaded the files, not in other accounts who are part of the shared folders.

I remember in earlier versions, face clustering was re-running for all users with file access. now, clustering is not re-running after moving files to a shared folder.

I just checked when this first occurred which was in January this year for me. I'm not always super fast with updates, but maybe this is a hint

**Comment by marcelklehr** [comment]
Hi @andreaskoelsch 
I'm sorry we haven't made much progress here. I will try to tackle this again.

**Comment by marcelklehr** [comment]
Could you try the following patch? https://github.com/nextcloud/recognize/pull/1569

**Comment by andreaskoelsch** [comment]
Thanks for your response, much appreciated! I'll create a new nextcloud instance to test this as I don't want to mess with my productive one. Will take a few days to try this.

**Comment by marcelklehr** [comment]
Ah, sorry. I've revised the patch a bit more. Here is the new PR: https://github.com/nextcloud/recognize/pull/1572
