### ISSUE TITLE
Can't save settings (returns HTTP 405)

### ISSUE THREAD

**Issue by utahbmxer** [nextcloud/recognize#464]
**Describe the bug**
Changing settings/toggles under Administrator > Recognize results in notification in upper right stating "Failed to save settings"

**To Reproduce**
1. Go to 'Administrator > Recognize', 
2. Click on 'Enable face recognition...'
3. See error "Failed to save settings"
4. Have enabled debug logging in NC25, and don't see any logs pertaining to this app

**Expected behavior**
Save settings?  (is this config.php or database??)

**Recognize (please complete the following information):**
 - JS-only mode: [e.g. Yes/No] Unsure
 - Enabled modes: Can't enable anything because of this issue, have downloaded models using occ.

**Server (please complete the following information):**
 - Nextcloud: 25.0.1
 - OS: CentOS Linux release 7.9.2009 (VM running in XCP-NG)
 - RAM: 15GB
 - Processor Architecture: 8 cores, (x86) Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz

**Additional context**
Server response is *405 - Method Not Allowed*.  Have disabled NAXSI WAF (OPNsense) that is sitting in front, even though there have been zero events there.  config.php is writable by nginx user.

**Comment by marcelklehr** [comment]
This should be fixed in the latest release. Let me know if it isn't.

**Comment by utahbmxer** [comment]
My issue isn't resolved, but I think I have something else going on.  My Nextcloud instance is several years old, but has no issues.  However, I get a 404 for the followning resource when loading the recognize settings page (GET https://nc.domain.com/apps/recognize/admin/nodejs).  I am working on just moving my instance to a new Debian server which hasn't shown this issue (at least in the demo Nextcloud I am using to setup the requirements).  My Centos 7 is getting long in the tooth, time to bury it.  lol
