### ISSUE TITLE
People list rendering is slow (Also when merging)

### ISSUE THREAD

**Issue by PriceChild** [nextcloud/recognize#523]
**Describe the bug**

Every time I load https://nextcloud/apps/photos/faces the list of people seems to be dynamically loaded.

My full collection hasn't completed scanning but there's at least a thousand detected people so far, many of whom I need to merge.

This is causing two annoying problems:
1. The list populates slowly, jumping around as it goes.
2. Huge CPU usage on the client rendering the thing.

I can see a couple of requests for each person, e.g. https://nextcloud/remote.php/dav/recognize/pricey/faces/519/ & https://nextcloud/apps/photos/api/v1/preview/12067?x=512&y=512 but the response times suggest most of the time is not spent waiting for these. e.g. they're sequential & a second apart, but only taking milliseconds for a response, indicating other processing time between?

If you continue to navigate within the same tab and maintain the session, subsequent pages (e.g. navigating in and out of people) don't seem to need the people list to be processed again. Annoyingly I seem to be then hitting a different bug sometimes where the people list just doesn't appear when choosing e.g. "Merge with another person" and I have to hit reload...

**To Reproduce**
1. Go to https://nextcloud/apps/photos/faces or open a person and choose the three dots and "merge with another person".
2. Wait...

**Expected behavior**
* Not having to wait as long for the list of people to render.
* Not having faces in the list jump around for 10 minutes while it renders.

**Recognize (please complete the following information):**
 - Installed app version: 3.2.3
 - WASM mode: No
 - Enabled modes: face recognition

**Server (please complete the following information):**
 - Nextcloud version: 25.0.1
 - OS: Ubuntu 20.04
 - Docker container (if applicable): No
 - RAM: 32GB
 - Processor Architecture ARM64

**Additional context**

**Comment by marcelklehr** [comment]
This should be fixed in v25.0.2

**Comment by elpraga** [comment]
I'm afraid there is no noticeable change. I‌'ve just updated to 25.0.2RC2 just to try this feature and I‌ cannot see any improvement. 

It takes 9 minutes and 25 sec on my computer to show the faces (and interact, open a person's folder). One of the CPU‌ cores is maxed out the whole time. 

Merging does not work at all, it just says "Merge person" on the top, but no bubbles to merge with are shown (not even after an hour of waiting ).

I'm running the server on an RPi 4 with 8GB of RAM, and I‌ do have quite a few photos, but a similar app ("Face Recognition") works like a charm on the same setup. (provided that I‌ had to compile the libs myself first)

I‌s there any chance of a real improvement that would make the app usable? I love the way it is integrated into Photos (in a much more seamless way than Face Recognition).

**Comment by elpraga** [comment]
BTW, tags within the Photos app are loaded much more quickly, there are also many on the same set of photos. (I have no clue if this detail is useful or not, I‌ added it just in case.)

**Comment by marcelklehr** [comment]
> I‌'ve just updated to 25.0.2RC2 just to try this feature and I‌ cannot see any improvement.

Mmmh. Then maybe the backports didn't happen and the fix is only scheduled for 26 so far. I'll look into it

**Comment by marcelklehr** [comment]
Indeed, I only just created the backport PR: https://github.com/nextcloud/photos/pull/1523 It will then be in v25.0.3

**Comment by elpraga** [comment]
Is there a way to update the Photos app manually on 25.0.2 ? 

I'm sorry, I'm not an expert, I couldn't understand how to do it by reading the PR.

Having this app working would be great and I could also test if merging works in the updated version.

**Comment by marcelklehr** [comment]
you can install the photos app manually by running the following steps
 
2. install git and node.js and composer
3. cd nextcloud/apps/
4. git clone https://github.com/nextcloud/photos
5. cd photos
6. git checkout stable25
7. composer install
8. npm ci
9. npm run build

**Comment by elpraga** [comment]
Thank you @marcelklehr ! I've not been able to try it yet, but I have discovered the "Memories" app that can also work with the data from Recognize (and it is usable ATM).

When I merged many people using Memories, "People" in the Photos app does not take so incredibly long to load. 

Nonetheless, the two apps do not share the exact same photos, and when I try to merge using the Photos app, it is not working. (the screen just dims, no people to choose from are shown to merge with)

Is this behaviour also going to be fixed in 25.0.3 or does this behaviour need to be reported separately?

**Comment by marcelklehr** [comment]
> Is this behaviour also going to be fixed in 25.0.3 or does this behaviour need to be reported separately?

Yep, it's fixed :)

**Comment by pjrobertson** [comment]
This still appears to be a problem for me, running:

Nextcloud: 27.0.2
Photos: 2.3.0
Recognize: 4.3.2

Loading the 'People' section in Photos takes about 10 minutes to load all the images. Happy to give someone access to debug if need be.

**Comment by danotrampus** [comment]
I have the same issue. When i try to load `https://example.com/apps/photos/faces` the server takes 3 minutes approximately to respond correctly. I have 57 faces with a total of 30k images associated.

Nextcloud: 27.1.1
Photos: 2.3.0
Recognize: 5.0.1
MySQL: 8.0.34

One thing that i found is that the server used almost 50% of the CPU in those 3 minutes, in order to process the request:

![image](https://github.com/nextcloud/recognize/assets/11494867/2a7973b4-bd2c-44a6-8017-dd86f8197ea3)

What can i do to help resolve this issue?

**Comment by marcelklehr** [comment]
@pjrobertson I would be happy to debug a little on your instance, feel free to send credentials via email (address is on my gh profile)

**Comment by MCMic** [comment]
Same here, Nextcloud 27.0.2, Recognize 5.0.1, the list is really slow to load, even the count of pictures for each face, which I’d expect to show immediatly is slow.
I’m wondering if it’s not a problem related to having lots of parallel requests at the same time.
But what’s weird to me is that when reloading it’s slow again while I’d expect the browser to have the pictures in the cache and not refetch them.

**Comment by Nairolf76** [comment]
NC AIO VM v7.12.1
Memories v6.2.2
Preview Generator v5.4.0
Recognize v5.0.3

Very slow to load all the faces, then when I click on a recognized face and want to merge it to an existant one, it takes a long time to generate the list of existant faces (it's reloading the full list every times, it does not seem to cache) and then a long time to show again the list of faces, etc.

**Comment by PeggyFree** [comment]
Hello, same problem here. 1mn to display the people list, then 1mn to display any one,  then 1mn again to go back to the people list, and so on. I have 10k photos. Another user have 1k photos, the people feature is pretty responsive for him. The rest of the app is smooth for all users.
I installed Recognize with its latest version in february, so it is a fresh install on Nextcloud V28.

Nextcloud Docker 28.0.5
Recognize 6.1.1
Preview Generator 5.5.0

Ryzen 5600G / SSD / 10Gb dedicated DDR4 for Nextcloud
